<?php

namespace HappybreakJeuConcoursBundle\Repository;

/**
 * RegistrationQuizzValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationQuizzValueRepository extends \Doctrine\ORM\EntityRepository
{
}
