services:
#    happybreak_jeu_concours.example:
#        class: HappybreakJeuConcoursBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    happybreak_jeu_concours.registration:
        class: HappybreakJeuConcoursBundle\Service\Registration
        arguments:
            - "@doctrine.orm.entity_manager"
