services:
#    happybreak_jeu_concours_admin.example:
#        class: HappybreakJeuConcoursAdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    admin.registration:
          class: HappybreakJeuConcoursAdminBundle\Admin\Registration
          arguments: [~, HappybreakJeuConcoursBundle\Entity\Registration, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, label: Registrations }
          public: true
    admin.shares:
              class: HappybreakJeuConcoursAdminBundle\Admin\Share
              arguments: [~, HappybreakJeuConcoursBundle\Entity\Share, ~]
              tags:
                  - { name: sonata.admin, manager_type: orm, label: Shares }
              public: true
    admin.question:
          class: HappybreakJeuConcoursAdminBundle\Admin\Question
          arguments: [~, HappybreakJeuConcoursBundle\Entity\Question, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, label: Questions }
          public: true
    admin.question-option:
          class: HappybreakJeuConcoursAdminBundle\Admin\QuestionOption
          arguments: [~, HappybreakJeuConcoursBundle\Entity\QuestionOption, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, label: Options }
          public: true